import { ABOUT_VALUES, CONTACT_INFO, GALLERY_IMAGES, ORIGIN_STORY, STORY_QUOTE, TEAM_MEMBERS } from '../config/content'
import { PageHeader } from '../components/ui/PageHeader'
import { OptimizedImage } from '../components/ui/OptimizedImage'
import { Icon } from '../components/ui/Icon'

export function About(){return <div className="about-page">
  <PageHeader title="Celebration is a form of care." subtitle="Birthday Bundles is a student-led 501(c)(3) nonprofit, based in Alpharetta, GA and serving children in the Atlanta area." />
  <section className="origin-story" aria-labelledby="origin-story-heading"><div className="section-container-wide origin-layout"><div className="origin-quote"><p>Why it matters</p><h2 id="origin-story-heading">“{STORY_QUOTE.text}”</h2><cite>{STORY_QUOTE.attribution}</cite><p className="origin-charity-id">Charity ID {CONTACT_INFO.charityId}</p></div><ol>{ORIGIN_STORY.map((chapter,index)=><li key={chapter.title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{chapter.title}</h3><p>{chapter.body}</p></div></li>)}</ol></div></section>
  <section className="values-ribbon" aria-labelledby="values-ribbon-heading"><div className="section-container-wide"><h2 id="values-ribbon-heading">What goes into every bundle</h2><div>{ABOUT_VALUES.map(value=><article key={value.title}><Icon name={value.icon} size={32}/><h3>{value.title}</h3><p>{value.description}</p></article>)}</div></div></section>
  <section className="team-editorial" aria-labelledby="team-editorial-heading"><div className="section-container-wide"><p className="chapter-kicker">Our team</p><h2 id="team-editorial-heading">The people behind the boxes.</h2><div className="team-editorial-grid">{TEAM_MEMBERS.map((member,index)=><article key={member.name} className={`team-member-${index+1}`}><OptimizedImage src={member.src} fallback={member.fallback} alt={`Portrait of ${member.name}`}/><div><h3>{member.name}</h3><p className="team-role">{member.role}</p></div></article>)}</div></div></section>
  <section className="about-gallery" aria-labelledby="about-gallery-heading"><div className="section-container-wide"><p>Memories made together</p><h2 id="about-gallery-heading">A celebration looks different every time.</h2><div className="about-gallery-grid">{GALLERY_IMAGES.map((image,index)=><figure key={image.src} className={`gallery-shot gallery-shot-${index+1}`}><OptimizedImage src={image.src} fallback={image.fallback} alt={image.alt}/><figcaption>Birthday Bundles community photo {index+1}</figcaption></figure>)}</div></div></section>
</div>}
